let start:string = "Hey Abu Hurairah, I have started learning TYPESCRIPT.";
console.log(start);
let my_name:string = "Shahzad Tabassum";
console.log(my_name);
let ver_1 = 1; let ver_2 = 2; 
let ver_3 = 3; let ver_4 = 4;
let ver_5 = 5; let ver_6 = 6;
let ver_7 = 7; let ver_8 = 8;
let ver_9 = 9; let ver_10 = 10;
let sum_all =ver_1+ver_2+ver_3+ver_4+ver_5+ver_6+ver_7+ver_8+ver_9+ver_10;
console.log("Sum of All",sum_all);
let Difference = ver_10-ver_1-ver_4;
console.log("Differance",Difference);
let multiply_all = ver_1*ver_2*ver_3*ver_4*ver_5*ver_6*ver_7*ver_8*ver_9*ver_10;
console.log ("Multiply of all",multiply_all);
let division = ver_10/ver_2;
console.log("Result of Division",division);
let given_result = sum_all+Difference-division*multiply_all/ver_10;
console.log("Given Result", given_result);